// xtask/docgen/dsse: Dead Simple Signing Envelope for forensic evidence.
//
// DSSE (https://github.com/secure-systems-lab/dsse) provides a standard
// format for signing arbitrary messages. We use it to sign generated
// documents so that every artifact carries a cryptographic proof of:
//   - Which tool version generated it
//   - When it was generated
//   - The exact content that was signed
//
// In forensic-parity work, this is essential: a receipt without a
// DSSE envelope cannot be trusted as evidence.

use serde::{Deserialize, Serialize};

/// A DSSE envelope as defined by the spec.
#[derive(Debug, Clone, Serialize, Deserialize)]
// DSSE scaffold — will be used when receipts are cryptographically signed
#[allow(dead_code)]
pub struct DsseEnvelope {
    /// The type of payload (e.g., "m4-rs-receipt-v1").
    pub payload_type: String,
    /// Base64-encoded payload.
    pub payload: String,
    /// List of signatures.
    pub signatures: Vec<DsseSignature>,
}

/// A DSSE signature.
#[derive(Debug, Clone, Serialize, Deserialize)]
// DSSE scaffold — will be used when receipts are cryptographically signed
#[allow(dead_code)]
pub struct DsseSignature {
    /// Key ID used for signing.
    pub keyid: String,
    /// Base64-encoded signature over PAE(payloadType, payload).
    pub sig: String,
}

/// Create a DSSE envelope with a simple HMAC-SHA256 signature.
///
/// In production, this would use asymmetric keys. For forensic purposes,
/// we use a project-specific HMAC key to prove that the document was
/// generated by our tooling.
// DSSE scaffold — will be used when receipts are cryptographically signed
#[allow(dead_code)]
pub fn sign_payload(payload_type: &str, payload: &str, key: &[u8]) -> DsseEnvelope {
    use sha2::Sha256;

    // Construct the Pre-Authenticated Encoding (PAE)
    let pae = format!(
        "DSSEv1 {} {} {} {}",
        payload_type.len(),
        payload_type,
        payload.len(),
        payload
    );

    // HMAC-SHA256 signature
    let mut mac = hmac::Hmac::<Sha256>::new_from_slice(key).expect("HMAC key should be valid");
    use hmac::Mac;
    mac.update(pae.as_bytes());
    let result = mac.finalize();
    let sig = base64_encode(&result.into_bytes());

    DsseEnvelope {
        payload_type: payload_type.to_string(),
        payload: base64_encode(payload.as_bytes()),
        signatures: vec![DsseSignature {
            keyid: "m4-rs-xtask-v1".to_string(),
            sig,
        }],
    }
}

/// Verify a DSSE envelope's signature.
// DSSE scaffold — will be used when receipts are cryptographically signed
#[allow(dead_code)]
pub fn verify_envelope(envelope: &DsseEnvelope, key: &[u8]) -> Result<(), String> {
    use sha2::Sha256;

    let payload_bytes = base64_decode(&envelope.payload).ok_or("invalid payload base64")?;
    let payload =
        String::from_utf8(payload_bytes).map_err(|e| format!("payload not UTF-8: {}", e))?;

    let pae = format!(
        "DSSEv1 {} {} {} {}",
        envelope.payload_type.len(),
        envelope.payload_type,
        payload.len(),
        payload
    );

    for sig in &envelope.signatures {
        let sig_bytes = base64_decode(&sig.sig).ok_or("invalid signature base64")?;

        let mut mac =
            hmac::Hmac::<Sha256>::new_from_slice(key).map_err(|e| format!("HMAC error: {}", e))?;
        use hmac::Mac;
        mac.update(pae.as_bytes());
        mac.verify_slice(&sig_bytes)
            .map_err(|_| format!("signature verification failed for keyid {}", sig.keyid))?;
    }

    Ok(())
}

/// Extract and decode the payload from a DSSE envelope.
// DSSE scaffold — will be used when receipts are cryptographically signed
#[allow(dead_code)]
pub fn extract_payload(envelope: &DsseEnvelope) -> Option<String> {
    let bytes = base64_decode(&envelope.payload)?;
    String::from_utf8(bytes).ok()
}

// DSSE scaffold — will be used when receipts are cryptographically signed
#[allow(dead_code)]
fn base64_encode(data: &[u8]) -> String {
    // Minimal base64 implementation
    const CHARS: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut result = String::new();
    let chunks = data.chunks(3);
    for chunk in chunks {
        let b0 = chunk[0] as u32;
        let b1 = if chunk.len() > 1 { chunk[1] as u32 } else { 0 };
        let b2 = if chunk.len() > 2 { chunk[2] as u32 } else { 0 };
        let triple = (b0 << 16) | (b1 << 8) | b2;

        result.push(CHARS[((triple >> 18) & 0x3F) as usize] as char);
        result.push(CHARS[((triple >> 12) & 0x3F) as usize] as char);

        if chunk.len() > 1 {
            result.push(CHARS[((triple >> 6) & 0x3F) as usize] as char);
        } else {
            result.push('=');
        }

        if chunk.len() > 2 {
            result.push(CHARS[(triple & 0x3F) as usize] as char);
        } else {
            result.push('=');
        }
    }
    result
}

// DSSE scaffold — will be used when receipts are cryptographically signed
#[allow(dead_code)]
fn base64_decode(s: &str) -> Option<Vec<u8>> {
    let chars: Vec<u8> = s.bytes().filter(|b| *b != b'=' && *b != b'\n').collect();
    let mut result = Vec::new();
    let mut buffer: u32 = 0;
    let mut bits: u32 = 0;

    for &c in &chars {
        let val = match c {
            b'A'..=b'Z' => c - b'A',
            b'a'..=b'z' => c - b'a' + 26,
            b'0'..=b'9' => c - b'0' + 52,
            b'+' => 62,
            b'/' => 63,
            _ => return None,
        };
        buffer = (buffer << 6) | val as u32;
        bits += 6;
        if bits >= 8 {
            bits -= 8;
            result.push((buffer >> bits) as u8);
            buffer &= (1 << bits) - 1;
        }
    }
    Some(result)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_dsse_roundtrip() {
        let key = b"m4-rs-forensic-key-2026";
        let payload = r#"{"court":"M4.CLI.1","verdict":"pass"}"#;

        let envelope = sign_payload("m4-rs-receipt-v1", payload, key);
        let extracted = extract_payload(&envelope).unwrap();

        assert_eq!(extracted, payload);
        verify_envelope(&envelope, key).expect("verification should pass");
    }

    #[test]
    fn test_dsse_verify_fails_with_wrong_key() {
        let key = b"correct-key-123";
        let wrong_key = b"wrong-key-456";
        let payload = "test";

        let envelope = sign_payload("test-type", payload, key);
        assert!(verify_envelope(&envelope, wrong_key).is_err());
    }

    #[test]
    fn test_base64_roundtrip() {
        let data = b"hello world!";
        let encoded = base64_encode(data);
        let decoded = base64_decode(&encoded).unwrap();
        assert_eq!(decoded, data);
    }
}
